# Generated by Django 3.2.19 on 2023-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gettyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
